### ISSUE TITLE
Migrating from beta 1.0.6 to 1.0.7 with problems

### ISSUE THREAD

**Issue by 1024mb** [johanneszab/TumblTwo#5]
So I was using the beta version of TumblTwo 1.0.6 and now when I tried to use the newest version it doesn't work well. Open last version and blog names and dates and practically all of the info is gone, check out:

![tumbltwo_2016-04-25_00-13-10](https://cloud.githubusercontent.com/assets/9301204/14774315/91035978-0a7a-11e6-98a2-0eab0b1f8c59.png)

Beta version it's working fine but I want to control the number of blogs to simultaneous crawl, any way to solve this?

Thanks, cheers, great app

**Comment by johanneszab** [comment]
Well, [this version](http://www.jzab.de/files/TumblTwo_old.exe) -- as also written on the page -- should do the trick, I think.

Edit: I've added a note that it should also work with the previous beta datasets to make things more clear.

Thanks for the comment. Let me know if it works out for you as I think i did not explicitly test it against the beta version.

**Comment by 1024mb** [comment]
Oh, I didn't read all, I though it was for TumlbOne only, thanks, it worked fine.
Also, are you planning on addin support for videos?
